export { HttpClient, ApiError, AUTH_UNAUTHORIZED_EVENT } from './http-client'
export type { StreamChunk, ServerChatSession, ServerMessage } from './http-client'
export type {
  Message,
  MessageSource,
  ToolTraceStep,
  TicketRef,
  ChatSession,
  IndexProgress,
  KnowledgeDocument,
  PromptItem,
  TicketItem,
  TicketUserBrief,
  TicketStaff,
  TicketDetail,
  TicketCommentItem,
  TicketStats,
  TicketDraft,
  TicketCategory,
  TicketCategoryStats,
  MessageFeedback,
  MessageFeedbackReason,
  FeedbackOverview,
  FeedbackReasonItem,
  AgentRunOverview,
  AgentRunItem,
  AgentRunDetail,
  AgentRunStep,
  ToolDistributionItem,
  ModelDistributionItem,
  DailyTokenStat,
  CompletionRequest,
  CompletionResponse,
  NavTab,
  AppSettings,
  AuthResponse,
  AuthUser,
} from '@servicedesk/types'
export { TICKET_CATEGORY_OPTIONS, FEEDBACK_REASON_OPTIONS } from '@servicedesk/types'
